# Generated by Django 6.0.6 on 2026-07-08 04:47

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to=pathlib.PurePosixPath('/home/cdr9/Projects/PixelAi/media/uploads')),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='predicted',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/home/cdr9/Projects/PixelAi/media/predicted')),
        ),
    ]
