# Generated by Django 6.0.6 on 2026-07-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_imageupload_image_alter_imageupload_predicted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='predicted',
            field=models.ImageField(blank=True, null=True, upload_to='predicted/'),
        ),
    ]
